### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by suprafun** [MZ195/Python-MultiProcessing-MapReduce#1]
Hello, under what license is this project released under ? I would like to study it to learn from it. Thank you.

**Comment by MZ195** [comment]
Hi suprafun, sure you can study it.
Have fun.

**Comment by suprafun** [comment]
Thank you so very much. If its possible, could you please upload any formal license (unlicense, MIT, GPL, whatever you prefer) to the repo. ? That way I (and others who might find it) can be sure of how I should treat this very cool project. Thank you.

**Comment by MZ195** [comment]
Thank you for your input.
I have added a license as suggested.

**Comment by suprafun** [comment]
Thank you so very much.
